// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQw1MAzZtV-pnl-6KuW_BzqkrRiYNknvk',
    appId: '1:607740044972:web:14a86f0eae76301b2ca109',
    messagingSenderId: '607740044972',
    projectId: 'shopa-f257f',
    authDomain: 'shopa-f257f.firebaseapp.com',
    storageBucket: 'shopa-f257f.appspot.com',
    measurementId: 'G-P5FFJQ4C9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDhEzeV5EDiHSlDRLzNGLuCDDBe45T0Q',
    appId: '1:607740044972:android:3ff816005efacfbe2ca109',
    messagingSenderId: '607740044972',
    projectId: 'shopa-f257f',
    storageBucket: 'shopa-f257f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzKxBEef51JPk4R3_3usw6hjJyf18dEw',
    appId: '1:607740044972:ios:11f971a3e8fc042d2ca109',
    messagingSenderId: '607740044972',
    projectId: 'shopa-f257f',
    storageBucket: 'shopa-f257f.appspot.com',
    iosBundleId: 'com.shopa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzKxBEef51JPk4R3_3usw6hjJyf18dEw',
    appId: '1:607740044972:ios:a802164ecf2b4ba62ca109',
    messagingSenderId: '607740044972',
    projectId: 'shopa-f257f',
    storageBucket: 'shopa-f257f.appspot.com',
    iosBundleId: 'com.example.shopa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQw1MAzZtV-pnl-6KuW_BzqkrRiYNknvk',
    appId: '1:607740044972:web:caa478f6bb95b7b42ca109',
    messagingSenderId: '607740044972',
    projectId: 'shopa-f257f',
    authDomain: 'shopa-f257f.firebaseapp.com',
    storageBucket: 'shopa-f257f.appspot.com',
    measurementId: 'G-F7CDFGE4DE',
  );
}
